### PR TITLE
[Feature] Collapse Group

### PR DESCRIPTION
**Pull request by erickriva**
- Added Collapse Group
- Example on example app

### CODE REVIEW

**Comment by erickriva** [comment]
Would need to bring some animations to give a smoother UI, but i don't have the expertise on that.

**Comment by erickriva** [comment]
If approved, need to add on Docs before close this PR.

**Comment by erickriva** [comment]
I'm trying to animate this Component, please let this PR open for now.

**Comment by jsartisan** [comment]
Yea sure. Take your time.

**Comment by erickriva** [comment]
This PR was included on #50

**Pull request closed without merging**
