### PR TITLE
[Feature] Add a search field to Select

### PR DESCRIPTION
**Pull request by erickriva**

### CODE REVIEW

**Comment by erickriva** [comment]
Sorry, my icons doesn't show because i'm on a Expo managed app.
But this is how it looks:

screenshot_20201211-125327
screenshot_20201211-125336
screenshot_20201211-125351

**Comment by erickriva** [comment]
To allow search (and searchfield be visible), the **searchableProps** prop must be filled.

### Example:
For this data format: `{ country: { name: "Brazil" }, code: 55 }`,
this will be the use: `searchableProps={["country.name", "code"]}`

**Comment by erickriva** [comment]
I need to run more tests but, until now, everything is OK.

**Comment by erickriva** [comment]
This PR also fixed a bug where open Select with `ref.current.open()` close Select modal automatically.

**Comment by jsartisan** [comment]
Thanks for the PR :D I'll review it shortly.

**Pull request merged**
