### PR TITLE
Example App Redesign

### PR DESCRIPTION
**Pull request by erickriva**
### Example App
- Screen to show each component
- Some example screens

### Magnus UI
- Fix RadioGroup onChange, value and defaultValue types
- Fix CheckboxGroup onChange type

### CODE REVIEW

**Comment by erickriva** [comment]
This PR depends on #41

**Comment by erickriva** [comment]
This PR depends on #41 to fully work, because there are some examples of using the search feature on Select,

**Comment by erickriva** [comment]
This is how it looks:

image

**Comment by erickriva** [comment]
Take a look on https://expo.io/@erickriva/projects/react-native-magnus-example

**Comment by jsartisan** [comment]
This is awesome!

**Comment by jsartisan** [comment]
@erickriva Are you discord?

**Comment by erickriva** [comment]
> @erickriva Are you on discord? 

I don't know well how to use, but i think you can find me with this info: "erickriva#5964"

**Pull request merged**
